# Generated by Django 2.1.5 on 2021-01-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210105_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverage',
            field=models.CharField(choices=[('Gl', 'Глазурь'), ('PL', 'Платина'), ('GD', 'Позолота')], default='GD', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='product',
            name='hit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='matherial',
            field=models.CharField(choices=[('ST', 'Коррозионно-стойкая сталь'), ('FR', 'Фарфор'), ('GL', 'Хрустальное стекло')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
