# Generated by Django 2.1.5 on 2021-01-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210106_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverage',
            field=models.CharField(choices=[('Глазурь', 'Глазурь'), ('Платина', 'Платина'), ('Позолота', 'Позолота')], default='Позолота', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='matherial',
            field=models.CharField(choices=[('Коррозионно-стойкая сталь', 'Коррозионно-стойкая сталь'), ('Фарфор', 'Фарфор'), ('Хрустальное стекло', 'Хрустальное стекло')], default='Хрустальное стекло', max_length=255),
        ),
    ]
